<$if(PageModel.Layout.LayoutMain)$>
	<$MasterLayouts/LayoutMain()$>
<$endif$>
<$if(PageModel.Layout.LayoutSecondary)$>
	<$MasterLayouts/LayoutSecondary()$>
<$endif$>
<$if(PageModel.Layout.LayoutLeftSidebar)$>
	<$MasterLayouts/LayoutLeftSidebar()$>
<$endif$>
<$if(PageModel.Layout.LayoutRightSidebar)$>
	<$MasterLayouts/LayoutRightSidebar()$>
<$endif$>
<$if(PageModel.Layout.LayoutPlain)$>
	<$MasterLayouts/LayoutPlain()$>
<$endif$>